const editor = document.querySelector("#editor"), lines = document.querySelector("#line-numbers"), output = document.querySelector("#output");
const fileName = document.querySelector("#file-name"), tabName = document.querySelector("#tab-name"), breadcrumb = document.querySelector("#breadcrumb");
const status = document.querySelector("#status"), saveState = document.querySelector("#save-state"), sidebarTitle = document.querySelector("#sidebar-title"), sidebarContent = document.querySelector("#sidebar-content"), problemCount = document.querySelector("#problem-count");
const terminalPanel = document.querySelector("#terminal-panel"), terminalOutput = document.querySelector("#terminal-output"), terminalForm = document.querySelector("#terminal-form"), terminalCommand = document.querySelector("#terminal-command");
let currentPath = null, projectPath = null, projectLabel = "ЛОИҲАИ КУШОДА", saveTimer = null, currentTree = [];
const escapeHtml = value => String(value).replace(/[&<>\"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[char]);
const refreshLines = () => lines.textContent = Array.from({ length: editor.value.split("\n").length }, (_, index) => index + 1).join("\n");
const setStatus = message => { status.textContent = message; saveState.textContent = message; };
function setFile(file) { currentPath = file.path; fileName.textContent = file.name; tabName.textContent = file.name; breadcrumb.innerHTML = `ЛОИҲА <span>›</span> ${escapeHtml(file.name)}`; editor.value = file.source; refreshLines(); setStatus("Кушода шуд"); localStorage.setItem("tajiklang.studio.draft", JSON.stringify({ name: file.name, source: file.source })); }
async function newFile() { const file = await window.studio.newFile(); if (file) { setFile(file); currentTree = [{ type: "file", name: file.name, path: file.path }]; showFiles(); } }
async function save() { const saved = await window.studio.save({ path: currentPath, source: editor.value }); if (saved) setFile({ ...saved, source: editor.value }); }
function showResult(result, action = "Иҷро") { const text = result.ok ? (result.output || "(натиҷа нест)") : (result.error || result.output || "Хатои номаълум"); output.textContent = text; output.classList.toggle("error", !result.ok); const problems = (text.match(/Хато[иҳо]*/giu) || []).length; problemCount.textContent = problems ? `(${problems})` : ""; setStatus(result.ok ? `${action} шуд` : "Хато ёфт шуд"); }
async function run() { setStatus("Иҷро мешавад…"); output.classList.remove("error"); output.textContent = "Иҷро мешавад…"; showResult(await window.studio.run({ path: currentPath, source: editor.value })); }
async function check() { setStatus("Санҷида мешавад…"); output.classList.remove("error"); output.textContent = "Санҷида мешавад…"; showResult(await window.studio.check({ path: currentPath, source: editor.value }), "Санҷиш"); }
function openTerminal() { document.querySelectorAll(".panel-tab").forEach(tab => tab.classList.toggle("active", tab.dataset.output === "terminal")); output.hidden = true; terminalPanel.hidden = false; terminalCommand.focus(); setStatus("Tajik terminal кушода шуд"); }
function closeTerminal() { output.hidden = false; terminalPanel.hidden = true; }
async function runTerminal(command) { terminalOutput.textContent += `\n\ntajik ❯ ${command}\n`; const result = await window.studio.terminal({ command, projectPath }); terminalOutput.textContent += result.ok ? (result.output || "Иҷро шуд.") : (result.error || result.output || "Хато"); terminalOutput.scrollTop = terminalOutput.scrollHeight; }
function autoSave() { clearTimeout(saveTimer); saveTimer = setTimeout(() => { localStorage.setItem("tajiklang.studio.draft", JSON.stringify({ name: tabName.textContent, source: editor.value })); setStatus("Худкор нигоҳ дошта шуд"); }, 650); }
function fileButton(file, depth = 0) { const row = document.createElement("button"); row.className = "file"; row.style.paddingInlineStart = `${8 + depth * 14}px`; row.innerHTML = `<span class="file-dot"></span><span>${escapeHtml(file.name)}</span>`; row.addEventListener("click", async () => file.path ? setFile(await window.studio.readFile(file.path)) : setFile({ path: null, name: file.name, source: editor.value })); return row; }
function tree(files, depth = 0) { const fragment = document.createDocumentFragment(); files.forEach(item => { if (item.type === "folder") { const heading = document.createElement("div"); heading.className = "tree-folder"; heading.style.paddingInlineStart = `${10 + depth * 14}px`; heading.textContent = `⌄ ${item.name}`; fragment.append(heading, tree(item.children, depth + 1)); } else fragment.append(fileButton(item, depth)); }); return fragment; }
async function openProject() { const project = await window.studio.openProject(); if (!project) return; projectPath = project.path; projectLabel = project.name; currentTree = project.files; showFiles(); setStatus(`Лоиҳаи «${project.name}» кушода шуд`); }
function showFiles() { sidebarTitle.textContent = "ФАЙЛҲО"; sidebarContent.innerHTML = `<div class="folder-title"><span class="chevron">⌄</span> ${escapeHtml(projectLabel)}</div><div id="file-list" class="file-list"></div><div class="next-note"><strong>TajikLang Next</strong><span>Дода, нишон ва блокҳои равшан</span><a href="https://github.com/BahromPython/tajiklang-2.0.0/blob/main/docs/TAJIKLANG_NEXT.md">Дастурро бинед</a></div>`; document.querySelector("#file-list").replaceChildren(currentTree.length ? tree(currentTree) : fileButton({ path: currentPath, name: tabName.textContent })); }
function setSidebar(panel) { document.querySelectorAll(".activity-button[data-panel]").forEach(button => button.classList.toggle("active", button.dataset.panel === panel)); if (panel === "files") return showFiles(); if (panel === "search") { sidebarTitle.textContent = "ҶУСТУҶӮ"; sidebarContent.innerHTML = `<div class="side-form"><input id="find-in-code" placeholder="Дар файли кушода ҷустуҷӯ кунед"><p>Матнро нависед ва Enter-ро пахш кунед.</p></div>`; document.querySelector("#find-in-code").addEventListener("keydown", event => { if (event.key !== "Enter") return; const term = event.target.value, index = editor.value.toLocaleLowerCase().indexOf(term.toLocaleLowerCase()); if (index < 0) return setStatus("Матн ёфт нашуд"); editor.focus(); editor.setSelectionRange(index, index + term.length); setStatus("Матн ёфт шуд"); }); return; } if (panel === "packages") { sidebarTitle.textContent = "БАСТАҲО"; sidebarContent.innerHTML = `<div class="side-form"><strong>Китобхонаи TajikLang</strong><pre id="package-list">Бастаҳо бор мешаванд…</pre><p class="side-note">Бастаҳо дар муҳити ҳамин лоиҳа насб мешаванд.</p></div>`; window.studio.packages({ projectPath }).then(result => { document.querySelector("#package-list").textContent = result.output || result.error || "Баста ёфт нашуд."; }); return; } sidebarTitle.textContent = "TAJIKBLOCKS"; sidebarContent.innerHTML = `<div class="side-form blocks-card"><strong>Барномасозии визуалӣ</strong><p>Блокҳо, тағйирёбандаҳо ва рамзи TajikLang дар як муҳити омӯзишӣ.</p><button id="blocks-help">TajikBlocks-ро оғоз кунед</button><p class="side-note">Лоиҳаи блокӣ: <code>tajik init blocks номи_лоиҳа</code></p></div>`; document.querySelector("#blocks-help").addEventListener("click", () => { output.textContent = "TajikBlocks: аз терминал «tajik блокҳо»-ро иҷро кунед. Дар навсозии оянда он пурра дар Studio ҷой мегирад."; setStatus("TajikBlocks омода аст"); }); }
editor.addEventListener("input", () => { refreshLines(); setStatus("Тағйир ёфт"); autoSave(); }); editor.addEventListener("scroll", () => lines.scrollTop = editor.scrollTop);
document.querySelector("#new-file").addEventListener("click", newFile); document.querySelector(".add-tab").addEventListener("click", newFile); document.querySelector("#open-file").addEventListener("click", async () => { const file = await window.studio.open(); if (file) setFile(file); }); document.querySelector("#open-project").addEventListener("click", openProject); document.querySelector("#run").addEventListener("click", run); document.querySelector("#activity-run").addEventListener("click", run); document.querySelector("#check").addEventListener("click", check);
document.querySelectorAll(".activity-button[data-panel]").forEach(button => button.addEventListener("click", () => setSidebar(button.dataset.panel))); document.querySelectorAll(".panel-tab").forEach(button => button.addEventListener("click", () => { document.querySelectorAll(".panel-tab").forEach(tab => tab.classList.toggle("active", tab === button)); if (button.dataset.output === "problems") { closeTerminal(); check(); } else if (button.dataset.output === "terminal") openTerminal(); else closeTerminal(); })); document.querySelector(".window-action").addEventListener("click", () => document.body.classList.toggle("theme-bright"));
terminalForm.addEventListener("submit", async event => { event.preventDefault(); const command = terminalCommand.value.trim(); if (!command) return; terminalCommand.value = ""; await runTerminal(command); });
document.addEventListener("keydown", event => { if (event.key === "F5") { event.preventDefault(); run(); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "s") { event.preventDefault(); save(); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "o") { event.preventDefault(); document.querySelector("#open-file").click(); } }); window.studio.onExternalFile(setFile); window.studio.onError(message => { output.textContent = message; output.classList.add("error"); setStatus("Хато"); });
window.studio.onMenu(action => { if (action === "new") newFile(); else if (action === "open") document.querySelector("#open-file").click(); else if (action === "project") openProject(); else if (action === "save") save(); else if (action === "run") run(); else if (action === "check") check(); else if (action === "terminal") openTerminal(); else if (action === "version") { openTerminal(); runTerminal("--version"); } else if (action === "files" || action === "search") setSidebar(action); else if (action === "theme") document.body.classList.toggle("theme-bright"); else if (action === "help") window.open("https://github.com/BahromPython/tajiklang-2.0.0/blob/main/docs/TAJIKLANG_NEXT.md", "_blank"); });
const draft = localStorage.getItem("tajiklang.studio.draft"); if (draft) { try { const file = JSON.parse(draft); if (file.source) setFile({ path: null, name: file.name || "барномаи нав.tj", source: file.source }); } catch (_) {} } refreshLines();
